server:
  port: 5555
  
spring:
  application:
    name: 'zuul'
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
       
zuul:
  sensitive-headers:
  - Cookie, Authorization 